apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true  
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.13.1
    helm:
      releaseName: keda
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keda
