apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-deployment
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dev
- target:
    group: ""
    version: v1
    kind: Service
    name: nginx-service
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dev
