apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: .*
    patch: |-
      - op: replace
        path: "/spec/source/targetRevision"
        value: "stage"
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: nginx
    patch: |-
      - op: replace
        path: "/spec/source/path"
        value: "ngnix/overlays/stage"
